language: node_js
#sudo: required
node_js:
    - "6"
dist: trusty

addons:
  postgresql: "9.6"

install:
    - nvm install 6

script:
    - (cd collector && npm install)
    - (cd collector && npm test)
